// AUTO GENERATED FILE, DO NOT EDIT.
// Generated by `flutter_rust_bridge`@ 1.45.0.
// ignore_for_file: non_constant_identifier_names, unused_element, duplicate_ignore, directives_ordering, curly_braces_in_flow_control_structures, unnecessary_lambdas, slash_for_doc_comments, prefer_const_literals_to_create_immutables, implicit_dynamic_list_literal, duplicate_import, unused_import, prefer_single_quotes, prefer_const_constructors, use_super_parameters, always_use_package_imports, annotate_overrides, invalid_use_of_protected_member, constant_identifier_names

import 'dart:convert';
import 'dart:async';
import 'package:flutter_rust_bridge/flutter_rust_bridge.dart';

import 'package:meta/meta.dart';
import 'package:meta/meta.dart';
import 'dart:ffi' as ffi;

abstract class SodiumKeyGenerator {
  Future<EdKeyPair> generateKey({dynamic hint});

  FlutterRustBridgeTaskConstMeta get kGenerateKeyConstMeta;

  Future<String> signMessage(
      {required String message, required String key, dynamic hint});

  FlutterRustBridgeTaskConstMeta get kSignMessageConstMeta;
}

class EdKeyPair {
  final String privKey;
  final String pubKey;

  EdKeyPair({
    required this.privKey,
    required this.pubKey,
  });
}

class SodiumKeyGeneratorImpl implements SodiumKeyGenerator {
  final SodiumKeyGeneratorPlatform _platform;
  factory SodiumKeyGeneratorImpl(ExternalLibrary dylib) =>
      SodiumKeyGeneratorImpl.raw(SodiumKeyGeneratorPlatform(dylib));

  /// Only valid on web/WASM platforms.
  factory SodiumKeyGeneratorImpl.wasm(FutureOr<WasmModule> module) =>
      SodiumKeyGeneratorImpl(module as ExternalLibrary);
  SodiumKeyGeneratorImpl.raw(this._platform);
  Future<EdKeyPair> generateKey({dynamic hint}) =>
      _platform.executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_generate_key(port_),
        parseSuccessData: _wire2api_ed_key_pair,
        constMeta: kGenerateKeyConstMeta,
        argValues: [],
        hint: hint,
      ));

  FlutterRustBridgeTaskConstMeta get kGenerateKeyConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "generate_key",
        argNames: [],
      );

  Future<String> signMessage(
          {required String message, required String key, dynamic hint}) =>
      _platform.executeNormal(FlutterRustBridgeTask(
        callFfi: (port_) => _platform.inner.wire_sign_message(port_,
            _platform.api2wire_String(message), _platform.api2wire_String(key)),
        parseSuccessData: _wire2api_String,
        constMeta: kSignMessageConstMeta,
        argValues: [message, key],
        hint: hint,
      ));

  FlutterRustBridgeTaskConstMeta get kSignMessageConstMeta =>
      const FlutterRustBridgeTaskConstMeta(
        debugName: "sign_message",
        argNames: ["message", "key"],
      );
}

// Section: api2wire

@protected
int api2wire_u8(int raw) {
  return raw;
}

// Section: wire2api

String _wire2api_String(dynamic raw) {
  return raw as String;
}

EdKeyPair _wire2api_ed_key_pair(dynamic raw) {
  final arr = raw as List<dynamic>;
  if (arr.length != 2)
    throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
  return EdKeyPair(
    privKey: _wire2api_String(arr[0]),
    pubKey: _wire2api_String(arr[1]),
  );
}

int _wire2api_u8(dynamic raw) {
  return raw as int;
}

Uint8List _wire2api_uint_8_list(dynamic raw) {
  return raw as Uint8List;
}

class SodiumKeyGeneratorPlatform
    extends FlutterRustBridgeBase<SodiumKeyGeneratorWire> {
  SodiumKeyGeneratorPlatform(ffi.DynamicLibrary dylib)
      : super(SodiumKeyGeneratorWire(dylib));
// Section: api2wire

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_String(String raw) {
    return api2wire_uint_8_list(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<wire_uint_8_list> api2wire_uint_8_list(Uint8List raw) {
    final ans = inner.new_uint_8_list_0(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }
// Section: api_fill_to_wire

}

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.

/// generated by flutter_rust_bridge
class SodiumKeyGeneratorWire implements FlutterRustBridgeWireBase {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  SodiumKeyGeneratorWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  SodiumKeyGeneratorWire.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void store_dart_post_cobject(
    DartPostCObjectFnType ptr,
  ) {
    return _store_dart_post_cobject(
      ptr,
    );
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
          'store_dart_post_cobject');
  late final _store_dart_post_cobject = _store_dart_post_cobjectPtr
      .asFunction<void Function(DartPostCObjectFnType)>();

  void wire_generate_key(
    int port_,
  ) {
    return _wire_generate_key(
      port_,
    );
  }

  late final _wire_generate_keyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
          'wire_generate_key');
  late final _wire_generate_key =
      _wire_generate_keyPtr.asFunction<void Function(int)>();

  void wire_sign_message(
    int port_,
    ffi.Pointer<wire_uint_8_list> message,
    ffi.Pointer<wire_uint_8_list> key,
  ) {
    return _wire_sign_message(
      port_,
      message,
      key,
    );
  }

  late final _wire_sign_messagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(ffi.Int64, ffi.Pointer<wire_uint_8_list>,
              ffi.Pointer<wire_uint_8_list>)>>('wire_sign_message');
  late final _wire_sign_message = _wire_sign_messagePtr.asFunction<
      void Function(
          int, ffi.Pointer<wire_uint_8_list>, ffi.Pointer<wire_uint_8_list>)>();

  ffi.Pointer<wire_uint_8_list> new_uint_8_list_0(
    int len,
  ) {
    return _new_uint_8_list_0(
      len,
    );
  }

  late final _new_uint_8_list_0Ptr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<wire_uint_8_list> Function(
              ffi.Int32)>>('new_uint_8_list_0');
  late final _new_uint_8_list_0 = _new_uint_8_list_0Ptr
      .asFunction<ffi.Pointer<wire_uint_8_list> Function(int)>();

  void free_WireSyncReturnStruct(
    WireSyncReturnStruct val,
  ) {
    return _free_WireSyncReturnStruct(
      val,
    );
  }

  late final _free_WireSyncReturnStructPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(WireSyncReturnStruct)>>(
          'free_WireSyncReturnStruct');
  late final _free_WireSyncReturnStruct = _free_WireSyncReturnStructPtr
      .asFunction<void Function(WireSyncReturnStruct)>();
}

class wire_uint_8_list extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

typedef DartPostCObjectFnType = ffi.Pointer<
    ffi.NativeFunction<ffi.Bool Function(DartPort, ffi.Pointer<ffi.Void>)>>;
typedef DartPort = ffi.Int64;
